language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t saoussen1987/docker-react -f Dockerfile.dev .

script:
  - docker run saoussen1987/docker-react npm run test -- --coverage
